### ISSUE TITLE
Как поле user может быть boolean?

### ISSUE THREAD

**Issue by Lindemann66** [k-a-b/study#4]
https://github.com/k-a-b/study/blob/6037da08dfbadd67385c757615a45ff81dd76705/three/db/migrate/20180927170240_create_messages.rb#L10

Непонятно, почему поле user стало boolean, с дефолтным значением true

**Comment by k-a-b** [comment]
Тут немного затупил, наверное хотел обозначить, что у сообщения должен быть автор
