### ISSUE TITLE
Почему cotent имеет тип boolean, и что значит это поле?

### ISSUE THREAD

**Issue by Lindemann66** [k-a-b/study#5]
https://github.com/k-a-b/study/blob/6037da08dfbadd67385c757615a45ff81dd76705/three/db/migrate/20180927170240_create_messages.rb#L11

Непонятно, что значит поле cotent, и почему оно boolean

**Comment by k-a-b** [comment]
content - содержание сообщения, как и с Userом, думал задать по умолчанию не пустое.
