### ISSUE TITLE
Что значит поле com_to_mes

### ISSUE THREAD

**Issue by Lindemann66** [k-a-b/study#6]
https://github.com/k-a-b/study/blob/6037da08dfbadd67385c757615a45ff81dd76705/three/db/migrate/20180927173628_create_comments.rb#L10

Непонятно, что значит поле com_to_mes, если выше уже есть текстовое поле content

**Comment by k-a-b** [comment]
Да, согласен -бред...сейчас сижу, смотрю на свою работу и сам недоумеваю как я такое сделал..
